### PR TITLE
use `client.js` when building prod

### PR DESCRIPTION
**Pull request by casio**
just spotted this one..leftover? : )

### CODE REVIEW

**Comment by YerkoPalma** [comment]
ups, I have been playing with some external repos haha, will fix in a minute so your tests will pass ;)

**Comment by YerkoPalma** [comment]
[Here](https://travis-ci.org/trainyard/choo-cli/builds/159934031), the build is passing :+1:

**Comment by conorcussell** [comment]
Just a heads up, this doesn't appear to be updated on the version on NPM yet!

**Comment by YerkoPalma** [comment]
cc: @MattMcFarland I guess this should bump in npm as @0.8.1

**Pull request merged**
